{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dpd.postgres.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dpd.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    {{- include "dpd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
{{- end }}
