{{- if and .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dpd.api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dpd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dpd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /api/metrics
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
{{- end }}
