apiVersion: v1
kind: Secret

metadata:
  name: demo-db-env
  namespace: default
  labels:
    app.kubernetes.io/part-of: demo-shop

type: Opaque

stringData:
  POSTGRES_DB: shop
  POSTGRES_USER: shop
  POSTGRES_PASSWORD: shop
