export enum ApiErrorCode {
  DEPLOYMENT_NOT_FOUND = 'DEPLOYMENT_NOT_FOUND',
  POD_NOT_FOUND = 'POD_NOT_FOUND',
  NAMESPACE_NOT_FOUND = 'NAMESPACE_NOT_FOUND',
  NAMESPACE_ALREADY_EXISTS = 'NAMESPACE_ALREADY_EXISTS',
  NAMESPACE_PROTECTED = 'NAMESPACE_PROTECTED',
  INGRESS_NOT_FOUND = 'INGRESS_NOT_FOUND',
  INGRESS_ALREADY_EXISTS = 'INGRESS_ALREADY_EXISTS',
  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  SERVICE_ALREADY_EXISTS = 'SERVICE_ALREADY_EXISTS',
  ROLLBACK_FAILED = 'ROLLBACK_FAILED',
  K8S_API_ERROR = 'K8S_API_ERROR',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  WEBHOOK_DISABLED = 'WEBHOOK_DISABLED',
  WEBHOOK_UNAUTHORIZED = 'WEBHOOK_UNAUTHORIZED',
  COMPOSE_PARSE_ERROR = 'COMPOSE_PARSE_ERROR',
  COMPOSE_IMPORT_FAILED = 'COMPOSE_IMPORT_FAILED',
  DOCKER_SCAN_UNAVAILABLE = 'DOCKER_SCAN_UNAVAILABLE',
}

export interface ApiErrorBody {
  code: ApiErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
