import { ContainerImageOption } from './types';

export const applicationImageOptions: ContainerImageOption[] = [
  { name: 'Argo CD', image: 'quay.io/argoproj/argocd:v2.13.0', category: 'Application', icon: 'argo', defaultPort: 8080 },
  { name: 'AWX', image: 'quay.io/ansible/awx:24.6.1', category: 'Application', icon: 'ansible', defaultPort: 8052 },
  { name: 'BookStack', image: 'lscr.io/linuxserver/bookstack:24.12.1', category: 'Application', icon: 'bookstack', defaultPort: 80 },
  { name: 'Consul', image: 'hashicorp/consul:1.20', category: 'Application', icon: 'consul', defaultPort: 8500 },
  { name: 'Discourse', image: 'discourse/discourse:3.3.3', category: 'Application', icon: 'discourse', defaultPort: 80 },
  { name: 'Drone CI', image: 'drone/drone:2.25', category: 'Application', icon: 'drone', defaultPort: 80 },
  { name: 'Drupal', image: 'drupal:11-apache', category: 'Application', icon: 'drupal', defaultPort: 80 },
  { name: 'Ghost', image: 'ghost:5-alpine', category: 'Application', icon: 'ghost', defaultPort: 2368 },
  { name: 'Gitea', image: 'gitea/gitea:1.22-rootless', category: 'Application', icon: 'gitea', defaultPort: 3000 },
  { name: 'GitLab CE', image: 'gitlab/gitlab-ce:17.6.0-ce.0', category: 'Application', icon: 'gitlab', defaultPort: 80 },
  { name: 'Home Assistant', image: 'ghcr.io/home-assistant/home-assistant:2024.12.0', category: 'Application', icon: 'homeassistant', defaultPort: 8123 },
  { name: 'Jenkins', image: 'jenkins/jenkins:2.479-jdk21', category: 'Application', icon: 'jenkins', defaultPort: 8080 },
  { name: 'Jitsi Web', image: 'jitsi/web:stable-9646', category: 'Application', icon: 'jitsi', defaultPort: 80 },
  { name: 'Joomla', image: 'joomla:5.2-apache', category: 'Application', icon: 'joomla', defaultPort: 80 },
  { name: 'Keycloak', image: 'quay.io/keycloak/keycloak:26.0', category: 'Application', icon: 'keycloak', defaultPort: 8080 },
  { name: 'Matomo', image: 'matomo:5.2-apache', category: 'Application', icon: 'matomo', defaultPort: 80 },
  { name: 'MediaWiki', image: 'mediawiki:1.43', category: 'Application', icon: 'mediawiki', defaultPort: 80 },
  { name: 'Metabase', image: 'metabase/metabase:v0.51.3', category: 'Application', icon: 'metabase', defaultPort: 3000 },
  { name: 'Moodle', image: 'moodle:4.5-apache', category: 'Application', icon: 'moodle', defaultPort: 80 },
  { name: 'Nextcloud', image: 'nextcloud:29-apache', category: 'Application', icon: 'nextcloud', defaultPort: 80 },
  { name: 'Nexus', image: 'sonatype/nexus3:3.75.0', category: 'Application', icon: 'sonatype', defaultPort: 8081 },
  { name: 'Odoo', image: 'odoo:18.0', category: 'Application', icon: 'odoo', defaultPort: 8069 },
  { name: 'Outline', image: 'outlinewiki/outline:0.82.0', category: 'Application', icon: 'outline', defaultPort: 3000 },
  { name: 'Paperless-ngx', image: 'ghcr.io/paperless-ngx/paperless-ngx:2.13.0', category: 'Application', icon: 'paperlessngx', defaultPort: 8000 },
  { name: 'Portainer', image: 'portainer/portainer-ce:2.21.4', category: 'Application', icon: 'portainer', defaultPort: 9000 },
  { name: 'Rocket.Chat', image: 'rocket.chat:6.12.0', category: 'Application', icon: 'rocketdotchat', defaultPort: 3000 },
  { name: 'SonarQube', image: 'sonarqube:10.7-community', category: 'Application', icon: 'sonarqube', defaultPort: 9000 },
  { name: 'Superset', image: 'apache/superset:4.1.0', category: 'Application', icon: 'apachesuperset', defaultPort: 8088 },
  { name: 'Vault', image: 'hashicorp/vault:1.18', category: 'Application', icon: 'vault', defaultPort: 8200 },
  { name: 'Vaultwarden', image: 'vaultwarden/server:1.32.5', category: 'Application', icon: 'bitwarden', defaultPort: 80 },
  { name: 'WordPress', image: 'wordpress:6.7-php8.2-apache', category: 'Application', icon: 'wordpress', defaultPort: 80 },
];
