import { ContainerImageOption } from './types';

export const databaseImageOptions: ContainerImageOption[] = [
  { name: 'ArangoDB', image: 'arangodb:3.12', category: 'Database', icon: 'arangodb', defaultPort: 8529 },
  { name: 'Cassandra', image: 'cassandra:5.0', category: 'Database', icon: 'apachecassandra', defaultPort: 9042 },
  { name: 'ClickHouse', image: 'clickhouse/clickhouse-server:24.8', category: 'Database', icon: 'clickhouse', defaultPort: 8123 },
  { name: 'CockroachDB', image: 'cockroachdb/cockroach:v24.2.0', category: 'Database', icon: 'cockroachlabs', defaultPort: 26257 },
  { name: 'CouchDB', image: 'couchdb:3.4', category: 'Database', icon: 'apachecouchdb', defaultPort: 5984 },
  { name: 'Dragonfly', image: 'docker.dragonflydb.io/dragonflydb/dragonfly:v1.25.4', category: 'Database', icon: 'dragonflydb', defaultPort: 6379 },
  { name: 'Elasticsearch', image: 'docker.elastic.co/elasticsearch/elasticsearch:8.15.0', category: 'Database', icon: 'elasticsearch', defaultPort: 9200 },
  { name: 'etcd', image: 'quay.io/coreos/etcd:v3.5.17', category: 'Database', icon: 'etcd', defaultPort: 2379 },
  { name: 'InfluxDB', image: 'influxdb:2.7-alpine', category: 'Database', icon: 'influxdb', defaultPort: 8086 },
  { name: 'MariaDB', image: 'mariadb:11.4', category: 'Database', icon: 'mariadb', defaultPort: 3306 },
  { name: 'Memcached', image: 'memcached:1.6-alpine', category: 'Database', icon: 'memcached', defaultPort: 11211 },
  { name: 'Milvus', image: 'milvusdb/milvus:v2.4.15', category: 'Database', icon: 'milvus', defaultPort: 19530 },
  { name: 'MongoDB', image: 'mongo:8.0', category: 'Database', icon: 'mongodb', defaultPort: 27017 },
  { name: 'MS SQL Server', image: 'mcr.microsoft.com/mssql/server:2022-latest', category: 'Database', icon: 'microsoftsqlserver', defaultPort: 1433 },
  { name: 'MySQL', image: 'mysql:8.4', category: 'Database', icon: 'mysql', defaultPort: 3306 },
  { name: 'Neo4j', image: 'neo4j:5.26-community', category: 'Database', icon: 'neo4j', defaultPort: 7474 },
  { name: 'Oracle XE', image: 'gvenzl/oracle-xe:21-slim', category: 'Database', icon: 'oracle', defaultPort: 1521 },
  { name: 'PostgreSQL', image: 'postgres:17-alpine', category: 'Database', icon: 'postgresql', defaultPort: 5432 },
  { name: 'PostgreSQL', image: 'postgres:16-alpine', category: 'Database', icon: 'postgresql', defaultPort: 5432 },
  { name: 'QuestDB', image: 'questdb/questdb:8.2.1', category: 'Database', icon: 'questdb', defaultPort: 9000 },
  { name: 'Qdrant', image: 'qdrant/qdrant:v1.12.5', category: 'Database', icon: 'qdrant', defaultPort: 6333 },
  { name: 'Redis', image: 'redis:7.4-alpine', category: 'Database', icon: 'redis', defaultPort: 6379 },
  { name: 'Redis', image: 'redis:7-alpine', category: 'Database', icon: 'redis', defaultPort: 6379 },
  { name: 'Redis Stack', image: 'redis/redis-stack:7.4.0-v1', category: 'Database', icon: 'redis', defaultPort: 6379 },
  { name: 'Solr', image: 'solr:9.7', category: 'Database', icon: 'apachesolr', defaultPort: 8983 },
  { name: 'TimescaleDB', image: 'timescale/timescaledb:latest-pg16', category: 'Database', icon: 'timescale', defaultPort: 5432 },
  { name: 'Valkey', image: 'valkey/valkey:8.0-alpine', category: 'Database', icon: 'valkey', defaultPort: 6379 },
  { name: 'Weaviate', image: 'semitechnologies/weaviate:1.27.0', category: 'Database', icon: 'weaviate', defaultPort: 8080 },
  { name: 'Zookeeper', image: 'zookeeper:3.9.3', category: 'Database', icon: 'apachezookeeper', defaultPort: 2181 },
];
