import { ContainerImageOption } from './types';

export const runtimeImageOptions: ContainerImageOption[] = [
  { name: 'Alpine', image: 'alpine:3.21', category: 'Runtime', icon: 'alpinelinux' },
  { name: 'Amazon Corretto', image: 'amazoncorretto:21-alpine', category: 'Runtime', icon: 'amazon', defaultPort: 8080 },
  { name: 'Amazon Linux', image: 'amazonlinux:2023', category: 'Runtime', icon: 'amazon' },
  { name: 'Bun', image: 'oven/bun:1.2-alpine', category: 'Runtime', icon: 'bun', defaultPort: 3000 },
  { name: 'Busybox', image: 'busybox:1.37', category: 'Runtime', icon: 'busybox' },
  { name: 'Debian', image: 'debian:12-slim', category: 'Runtime', icon: 'debian' },
  { name: 'Deno', image: 'denoland/deno:alpine-2.2.0', category: 'Runtime', icon: 'deno', defaultPort: 8000 },
  { name: 'Erlang/OTP', image: 'erlang:27-alpine', category: 'Runtime', icon: 'erlang', defaultPort: 8080 },
  { name: 'Fedora', image: 'fedora:41', category: 'Runtime', icon: 'fedora' },
  { name: 'Go', image: 'golang:1.24-alpine', category: 'Runtime', icon: 'go', defaultPort: 8080 },
  { name: 'Java (OpenJDK)', image: 'eclipse-temurin:21-jre-alpine', category: 'Runtime', icon: 'openjdk', defaultPort: 8080 },
  { name: 'Node.js', image: 'node:22-alpine', category: 'Runtime', icon: 'nodedotjs', defaultPort: 3000 },
  { name: 'Node.js', image: 'node:20-alpine', category: 'Runtime', icon: 'nodedotjs', defaultPort: 3000 },
  { name: 'Node.js', image: 'node:18-alpine', category: 'Runtime', icon: 'nodedotjs', defaultPort: 3000 },
  { name: 'Perl', image: 'perl:5.40-slim', category: 'Runtime', icon: 'perl', defaultPort: 8080 },
  { name: 'PHP', image: 'php:8.4-apache', category: 'Runtime', icon: 'php', defaultPort: 80 },
  { name: 'PHP-FPM', image: 'php:8.4-fpm-alpine', category: 'Runtime', icon: 'php', defaultPort: 9000 },
  { name: 'Python', image: 'python:3.13-slim', category: 'Runtime', icon: 'python', defaultPort: 8000 },
  { name: 'Python', image: 'python:3.12-slim', category: 'Runtime', icon: 'python', defaultPort: 8000 },
  { name: 'Python', image: 'python:3.11-slim', category: 'Runtime', icon: 'python', defaultPort: 8000 },
  { name: 'Ruby', image: 'ruby:3.4-slim', category: 'Runtime', icon: 'ruby', defaultPort: 3000 },
  { name: 'Rust', image: 'rust:1.84-slim', category: 'Runtime', icon: 'rust', defaultPort: 8080 },
  { name: 'Apache Tomcat', image: 'tomcat:11.0-jdk21', category: 'Runtime', icon: 'apachetomcat', defaultPort: 8080, keywords: ['apache', 'tomcat'] },
  { name: 'Ubuntu', image: 'ubuntu:24.04', category: 'Runtime', icon: 'ubuntu' },
  { name: '.NET', image: 'mcr.microsoft.com/dotnet/aspnet:9.0', category: 'Runtime', icon: 'dotnet', defaultPort: 8080 },
  { name: '.NET', image: 'mcr.microsoft.com/dotnet/aspnet:8.0', category: 'Runtime', icon: 'dotnet', defaultPort: 8080 },
];
